---
abstract: 'An object representing a series of SQL statements, normally'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0.80
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: SQL::Script
name: SQL-Script
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Params::Util: 0.10
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/SQL-Script
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/SQL-Script
version: 1.06
