--- 
abstract: An object representing a series of SQL statements, normally
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  File::Spec: 0.80
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: SQL-Script
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Params::Util: 0.10
  perl: 5.6.0
version: 0.04
